### ISSUE TITLE
Missing awkward includes path

### ISSUE THREAD

**Issue by forthommel** [HEP-FCC/FCCAnalyses#137]
Dear all,
It appears the `awkward` API changed in the current (spackages5) SW stack, and does not provide any C++ interface anymore.

Thus, both `analyzers/dataframe/awkwardtest.cc` and `analyzers/dataframe/myUtils.cc` now fail to compile in master branch (missing `awkward/{Content,io/json,array/NumpyArray,...}.h` includes).

Am I the only one facing this now? :)

Cheers, Laurent

**Comment by vvolkl** [comment]
Hi Laurent,

no, that's a known issue with awkward, and we're still trying to come up with a long-term fix. I just patched the setup script with a workaround, so it should work again, please try again in a few minutes.

**Comment by forthommel** [comment]
Many many thanks, @vvolkl !

**Comment by forthommel** [comment]
As the upgraded stack fixes the problem, let me close this issue. Thanks a lot again for the fast reaction @vvolkl!
