### ISSUE TITLE
Missing library when running stage1 analysis.

### ISSUE THREAD

**Issue by AidanWiederhold** [HEP-FCC/FCCAnalyses#149]
When running a stage1 analysis script which loads the following on startup
```python
print ("Load cxx analyzers ... ",)
ROOT.gSystem.Load("libedm4hep")
ROOT.gSystem.Load("libpodio")
ROOT.gSystem.Load("libawkward")
ROOT.gSystem.Load("libawkward-cpu-kernels")
ROOT.gSystem.Load("libFCCAnalyses")

ROOT.gErrorIgnoreLevel = ROOT.kFatal
_edm  = ROOT.edm4hep.ReconstructedParticleData()
_pod  = ROOT.podio.ObjectID()
_fcc  = ROOT.dummyLoader

print ('edm4hep  ',_edm)
print ('podio    ',_pod)
print ('fccana   ',_fcc)
```
we (@matthewkenzie and I) are getting the following error

```bash
cling::DynamicLibraryManager::loadLibrary(): libPhysics.so.6.26: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/storage/epp2/phutmn/FCC/FCCAnalyses/examples/FCCee/flavour/b2snunu/./scripts/stage1.py", line 15, in <module>
    _fcc  = ROOT.dummyLoader
  File "/cvmfs/sw.hsf.org/spackages5/root/6.26.02/x86_64-centos7-gcc11.2.0-opt/oqvm2/lib/ROOT/_facade.py", line 195, in _fallback_getattr
    raise AttributeError("Failed to get attribute {} from ROOT".format(name))
AttributeError: Failed to get attribute dummyLoader from ROOT
```

Has something changed in the CMake somewhere such that the expected library is no longer where it thinks it should be?

**Comment by kjvbrt** [comment]
The problem can be also solved by sourcing nightly version of the FCC environment

**Comment by AidanWiederhold** [comment]
Do you mean doing `source /cvmfs/fcc.cern.ch/sw/latest/setup.sh`? When I start a fresh shell I do
```
cd FCCeePhysicsPerformance/case-studies/flavour/tools
source /cvmfs/fcc.cern.ch/sw/latest/setup.sh
source ./localSetup.sh $PWD/localPythonTools
cd ../../../../FCCAnalyses/
source ./setup.sh
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=../install
make install
```

**Comment by AngLICERN** [comment]
> 

Hi @AidanWiederhold 

We also encountered this issue.
Solved by replacing 

`source /cvmfs/fcc.cern.ch/sw/latest/setup.sh`

to

`source /cvmfs/sw.hsf.org/spackages5/key4hep-stack/2022-03-30/x86_64-centos7-gcc11.2.0-opt/mrwoj/setup.sh`

**Comment by kjvbrt** [comment]
The `/cvmfs/fcc.cern.ch/sw/latest/setup.sh` is a simlink to the `/cvmfs/sw.hsf.org/key4hep/setup.sh`
which is sourced in the `setup.sh` of the FCCAnalysis
```sh
lrwxrwxrwx. 1 cvmfs cvmfs 34 Sep 20  2020 /cvmfs/fcc.cern.ch/sw/latest/setup.sh -> /cvmfs/sw.hsf.org/key4hep/setup.sh
```
If one changes it to the `source /cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh` it should run fine.

**Comment by clementhelsens** [comment]
Hi @kjvbrt , I don't think we want FCCAnalyses to depend on nightly builds, but rather on latest published releases

**Comment by vvolkl** [comment]
Just as an explanation, previous releases (and the current nightlies) set the LD_LIBRARY_PATH and CPATH variables for everything, while the latest release uses RPATHs except for packages building ROOT dictionaries. With the current master branch, you should be able to use the latest release again
