### ISSUE TITLE
Using chunks option with analysis_final 

### ISSUE THREAD

**Issue by amanmdesai** [HEP-FCC/FCCAnalyses#299]
Hello @kjvbrt,

 I would like to report  another bug in continuation of #296  when using analysis_final with chunks of files:

## Problem
As I see number of processed events is calculated as follows (when using chunks option):

```python
                processEvents[process_id], eventsTTree[process_id] = get_entries(filepath)
```
[LINK TO CODE](https://github.com/HEP-FCC/FCCAnalyses/blob/2422e7e4b8cd8f99646f5a53e138b2c712dcfef7/python/FCCAnalysisRun.py#L645C29-L645C29)

However this number seems to correspond to the first chunk file only (`chunk0`) and not the entire set of chunks for that given process 

Example: I am running analysis final over the ssH_HZZ folder which consist of two chunks (chunk0 and chunk1), in this case the number of processed events printed on terminal is given as 

```code
Processed events: {'wzp6_ee_ssH_HZZ_ecm240': 300000,..... other files
```

## Expected Output
However I am scanning over **600000** events. 

## Another Problem
Moreover this also affects scaling of number of events: 

For instance,  the scaled number of events when using nChunks = 2 is half the number of scaled events expected (using the same equation).  (Please note that I am using doScale = True with the option intLumi).

## Possible Solution:
Compute  processEvents variable for a given process outside the `for filepath in flist` loop.

----------------

Could you please clarify on this one?

Thanks
Aman

**Comment by kjvbrt** [comment]
Hello @amanmdesai,

Can you try replacing `=` with `+=`:
```
645                  processEvents[process_id], eventsTTree[process_id] += get_entries(filepath)
```
The original number of events is stored in individual root files. This is not very reliable and will need to change.

**Comment by amanmdesai** [comment]
Hi @kjvbrt Thanks for your reply. 

That change resolves my problem

Thank you!

**Comment by amanmdesai** [comment]
Hi,
shall I open a PR to fix this?

**Comment by kjvbrt** [comment]
Why not :)
