### ISSUE TITLE
Center-of-mass energy used instead of lumi in text displayed in plots 

### ISSUE THREAD

**Issue by amagnan** [HEP-FCC/FCCAnalyses#314]
Dear experts,

it seems these two lines should not use "param.energy" or it is used instead of the integrated lumi in the text displayed in the plots:

https://github.com/HEP-FCC/FCCAnalyses/blob/b9696683b3f157696bf545a257326aef6b5627fa/python/doPlots.py#L216
https://github.com/HEP-FCC/FCCAnalyses/blob/b9696683b3f157696bf545a257326aef6b5627fa/python/doPlots.py#L352

Best,
AM.

**Comment by kjvbrt** [comment]
Thanks @armin-ilg for reporting :)
