### ISSUE TITLE
Error with fccanalysis plots <.py>

### ISSUE THREAD

**Issue by amanmdesai** [HEP-FCC/FCCAnalyses#324]
Hi,

This is to report that I see the following error when using the latest version (master branch) of FCCAnalyses for plots: 

```
  File "<path>/FCCAnalyses/install/bin/fccanalysis", line 96, in <module>
    main()
  File "<path>/FCCAnalyses/install/bin/fccanalysis", line 92, in main
    run(parser)
  File "<path>/FCCAnalyses/install/python/FCCAnalysisRun.py", line 1110, in run
    if args.eloglevel != "kUnset":
AttributeError: 'Namespace' object has no attribute 'eloglevel'
```

where "path" is the variable where I have installed the latest version of FCCAnalyses.

**Comment by kjvbrt** [comment]
Hi @amanmdesai,
the problem should be fixed by this PR https://github.com/HEP-FCC/FCCAnalyses/pull/326 .

**Comment by amanmdesai** [comment]
Thank you @kjvbrt
